/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org01.apkgen;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class string {
        public static final int dialog_message_install_runtime_lib=0x7f030007;
        public static final int dialog_message_update_runtime_lib=0x7f030003;
        public static final int dialog_message_update_runtime_lib_warning=0x7f030005;
        public static final int dialog_title_install_runtime_lib=0x7f030006;
        public static final int dialog_title_update_runtime_lib=0x7f030002;
        public static final int dialog_title_update_runtime_lib_warning=0x7f030004;
        public static final int download_from_store=0x7f030001;
        public static final int download_from_url=0x7f030000;
    }
}
